### ISSUE TITLE
Error With Invalid AWS Aauthentication

### ISSUE THREAD

**Issue by kgao** [JoseBarrios/mturk-api#10]
Current API assume the access id / key setup correctly, when user use an invalid AWS authentication id or key, it throws the error
``` 
W20160406-11:11:55.969(-4)? (STDERR) TypeError: Cannot read property '0' of undefined
W20160406-11:11:55.969(-4)? (STDERR)     at ... \mturk-api\index.js:75:59    
 ``` 
would you consider to fix this? Thank you!

**Comment by kgao** [comment]
I have a fix from my fork  -> https://github.com/JoseBarrios/mturk-api/pull/9

**Comment by JoseBarrios** [comment]
Merged your fix into the main branch. Thanks for taking care of this, @kgao!
