### ISSUE TITLE
Replace SOAP with REST

### ISSUE THREAD

**Issue by JoseBarrios** [JoseBarrios/mturk-api#12]
Amazon is slowly deprecating SOAP in favor of REST. They've already [done away with SOAP completely for EC2](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/using-soap-api.html).  It is critical that we start planning ahead for a potential SOAP deprecation in MTurk.

Currently, MTurk SOAP requests are not supported with [IAM](http://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html?icmpid=docs_iam_console). This means that, because we use SOAP, users need to use their root keys in order to make MTurk requests using our API. When we migrate to REST root keys will still work, but they will no longer be the only option.

Please let me know your thoughts, comments or concerns.

**Comment by JoseBarrios** [comment]
Done!

**Comment by ctrlcctrlv** [comment]
Mine was REST from day one ;-)

https://github.com/ctrlcctrlv/mturk-python

Why did you undo this in https://github.com/JoseBarrios/mturk-api/commit/3b852fb51b2b016f38b06d59bd1c689f5e024554 ?

**Comment by DVassilev** [comment]
@JoseBarrios Any answer to @ctrlcctrlv question?
