### ISSUE TITLE
cache wsdl file

### ISSUE THREAD

**Issue by contra** [JoseBarrios/mturk-api#2]
pulling down 200kb every startup is slow and a waste of bandwidth. should either be cached or stored locally.

i saw the commit where you removed it locally and i think thats a really bad idea. if the module mturk-api isn't tied to any specific API version, then lets say one day amazon changes the data it returns and now your code breaks randomly in production because this module is always using the latest version no matter what

**Comment by JoseBarrios** [comment]
That's fair. I've added the WSDL file back to the schemas folder, and I've also added its JSON schema equivalent for unit testing down the road.

**Comment by contra** [comment]
@JoseBarrios Thanks! The issue is fixed.
