### ISSUE TITLE
dont minify

### ISSUE THREAD

**Issue by contra** [JoseBarrios/mturk-api#3]
why is this minified before being published? it makes stacktraces unusable

**Comment by JoseBarrios** [comment]
I've changed the main file to not be minified. You can see the commit here: [d678e79](https://github.com/JoseBarrios/mturk-api/commit/d678e7963a31a5980029d0f8bcc4b430b9818c6d). I'll close this issue as soon as you confirmed if these changes addressed all your concerns. Thanks for submitting the issue!

**Comment by contra** [comment]
@JoseBarrios Thanks! The issue is fixed.
